ingress:
  hostname: dmm.platform.moleculemaker.org
  extraHosts:
  - dmm.frontend.mmli1.ncsa.illinois.edu
  - dmm.moleculemaker.org
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: "dmm-dmm-prod-domain-redirect@kubernetescrd"

config:
  hostname: "https://dmm.fastapi.mmli1.ncsa.illinois.edu"

extraDeploy:
- apiVersion: traefik.containo.us/v1alpha1
  kind: Middleware
  metadata:
    name: dmm-prod-domain-redirect
    namespace: dmm
  spec:
    redirectRegex:
      regex: "^https://(dmm.frontend.mmli1.ncsa.illinois.edu|dmm.moleculemaker.org)/(.*)"
      replacement: "https://dmm.platform.moleculemaker.org/${2}"
      permanent: true

