[tool.poetry]
name = "dmm-precomputation"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.1"
openpyxl = "^3.1.2"
numpy = "^1.26.4"
rdkit = "^2023.9.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
