# Defines the deployment of the app running in a pod on any worker node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: dmm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dmm-frontend
  template:
    metadata:
      labels:
        app: dmm-frontend
    spec:
      containers:
        - name: dmm-frontend
          image: {{ .Values.controller.image }}

          ports:
            - containerPort: 80
          imagePullPolicy: Always
